### PR TITLE
Update user.py

### PR DESCRIPTION
**Pull request by MORImementos**
edit reset password link

In case I messed something up, the link for the reset is supposed to be:

https://project-rio-frontend.vercel.app

/login/reset_password/**code that gets sent sent via email**

### CODE REVIEW

**Review by CNace13 — APPROVED** [review]

**Review by CNace13 — CHANGES_REQUESTED** [review]
Hey Mori, can you parameterize the URL un user.py? You can make a new variable in consts.py for it. This way we only have to change it in one place when we switch to the official url

**Comment by MORImementos** [comment]
do you want the password reset link itself or the base url

for ex, url = https://project-rio-frontend.vercel.app/ 
and add the password reset portion

or url = https://project-rio-frontend.vercel.app/login/reset_password/codesentinemail

**Comment by ProjectRio** [comment]
@MORImementos just the base url. If the password reset url changes we'll need to change the section you changed anyway. But the base should be a const

**Review by CNace13 — APPROVED** [review]

**Comment by CNace13** [comment]
Perfect, thanks Mori

**Pull request merged**
