### PR TITLE
Populate db endpoint

### PR DESCRIPTION
**Pull request by jonslui**

### CODE REVIEW

**Comment by CNace13** [comment]
Jon is this ready go in? I noticed that the star info is not calculated, would you like me to code that up in the new poulate_db function? 
```
offensive_star_swings = 0,
offensive_stars_used = 0,
offensive_stars_put_in_play = 0,
offensive_star_successes = 0,
offensive_star_chances = 0,
offensive_star_chances_won = 0,
defensive_star_pitches = 0,
defensive_stars_used = 0,
defensive_star_successes = 0,
defensive_star_chances = 0,
defensive_star_chances_won = 0
```

**Comment by jonslui** [comment]
Everything but the stat info is ready to go. Feel free to add it in if you want, otherwise I'll get it done tomorrow.

**Comment by CNace13** [comment]
I am going to hook up those stats. Then we'll merge this

**Comment by jonslui** [comment]
Sounds great

**Comment by CNace13** [comment]
Star stats are now calculated and stored to db in populate_db(). Jon can you double check me and then merge if everything looks okay? 

On to stat retrieval!

**Comment by jonslui** [comment]
Looks great!

**Pull request merged**
